-- Deprecated security stub.
-- Do not disable RLS for the storefront.
-- Use the maintained policy files in supabase/sql/ instead:
--   supabase/sql/02_rls_policies.sql
--   supabase/sql/03_storage.sql
