-- Deprecated security stub.
-- This file used broad admin policies.
-- Use the maintained files instead:
--   supabase/sql/01_schema.sql
--   supabase/sql/02_rls_policies.sql
--   supabase/sql/03_storage.sql
