-- Deprecated security stub.
-- Do not run old anonymous upload or RLS-disable policies.
-- Use the maintained policy files in supabase/sql/ instead:
--   supabase/sql/02_rls_policies.sql
--   supabase/sql/03_storage.sql
